/* Friendly Cars Dealership Queries */

-- What is the total sales amount generated by each salesperson?
 
SELECT CarSalesperson.empId, CarSalesperson.firstName, CarSalesperson.lastName, SUM(CarSale.salePrice) AS TotalSales
FROM CarSalesperson, CarSale
WHERE CarSalesperson.empId = CarSale.empId
GROUP BY CarSalesperson.empId, CarSalesperson.firstName, CarSalesperson.lastName;


-- What is the average list price of new cars grouped by their make?
 
SELECT make, AVG(listPrice) AS AverageListPrice
FROM CarNewCar
GROUP BY make;


-- Find the total number of cars registered and calculate the average fee for all car registrations.

SELECT COUNT(*) AS TotalRegistrations, AVG(fee) AS AverageFee
FROM CarRegistration;


-- Find the total amount financed by each financing company and order the results by the total in descending order.

SELECT companyName, SUM(AmountFinanced) AS TotalFinanced
FROM CarFinancing
GROUP BY companyName
ORDER BY TotalFinanced DESC;


-- Which customizations are associated with each VIN of the new cars?

SELECT   cn.VIN, cn.Make, cn.Model,  co.carOption
FROM  CarNewCar cn, CarNewCarOptions cno,   CarOptionsMenu co
WHERE   cn.VIN = cno.VIN
AND   cno.carOption = co.carOption
ORDER BY  cn.VIN; 


-- What is the total advertising cost for each area code?

SELECT areaCode, SUM(totalCost) AS total_ad_cost
FROM CarAd
GROUP BY areaCode
ORDER BY areaCode;
 

-- Which customers were referred by others, and what ads did they see?

SELECT cc.firstName || ' ' || cc.lastName AS customer_name, cc.adSeen, cc.referredBy
FROM CarCustomer cc
WHERE cc.referredBy IS NOT NULL
ORDER BY customer_name;
 

-- Which financing companies offer the lowest average interest rates?

SELECT companyName, AVG(rate) AS avg_interest_rate
FROM CarFinancing
GROUP BY companyName
ORDER BY avg_interest_rate ASC;
 

-- List the sales with the highest commissions for each salesperson, showing the salesperson’s name, the sale’s invoice number, and the commission amount.

SELECT s.firstName || ' ' || s.lastName AS salesperson_name,csale.invoiceNo,csale.commission
FROM CarSale csale
JOIN CarSalesperson s ON csale.empId = s.empId
WHERE (csale.empId, csale.commission) IN (
    SELECT empId, MAX(commission)
    FROM CarSale
    GROUP BY empId
);
 

-- What is the average sale price of cars sold, grouped by salesperson?

SELECT sp.firstName || ' ' || sp.lastName AS salesperson_name, AVG(cs.salePrice) AS average_sale_price
FROM CarSale cs
JOIN CarSalesperson sp ON cs.empId = sp.empId
GROUP BY sp.firstName, sp.lastName
ORDER BY average_sale_price DESC;